package org.zkoss.zktest.test2.theme.ipad;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public class Zul2ScalaVisionTestConverter {
	
	public static String srcPath = "C:/home/Neil/prj/f61/zkthemes/zkthemedemo/src/main/webapp/ipad_vision";
	public static String dstPath = "C:/home/Neil/prj/ztltest/vision_tablet/org/zkoss/zktest/test2/theme/ios";
	
	public static String[][] mappings = {
		{"anchor-caption-disabled", "IVT_Anchor_Caption_Disabled_Test"},
		{"anchor-caption-normal", "IVT_Anchor_Caption_Normal_Test"},
		{"anchor-disabled", "IVT_Anchor_Disabled_Test"},
		{"anchor-normal", "IVT_Anchor_Normal_Test"},
		{"bandbox-default-listbox", "IVT_Bandbox_Default_Listbox_Test"},
		{"bandbox-default-simple", "IVT_Bandbox_Default_Simple_Test"},
		{"bandbox-rounded-listbox", "IVT_Bandbox_Rounded_Listbox_Test"},
		{"bandbox-rounded-simple", "IVT_Bandbox_Rounded_Simple_Test"},
		{"biglistbox-multiplecolumn-1", "IVT_Biglistbox_Multiplecolumn_1_Test"},
		{"biglistbox-multiplecolumn-1-frozen", "IVT_Biglistbox_Multiplecolumn_1_Frozen_Test"},
		{"biglistbox-multiplecolumn-min", "IVT_Biglistbox_Multiplecolumn_Min_Test"},
		{"biglistbox-multiplecolumn-min-frozen", "IVT_Biglistbox_Multiplecolumn_Min_Frozen_Test"},
		{"biglistbox-multipleheader-1", "IVT_Biglistbox_Multipleheader_1_Test"},
		{"biglistbox-multipleheader-1-frozen", "IVT_Biglistbox_Multipleheader_1_Frozen_Test"},
		{"biglistbox-multipleheader-min", "IVT_Biglistbox_Multipleheader_Min_Test"},
		{"biglistbox-multipleheader-min-frozen", "IVT_Biglistbox_Multipleheader_Min_Frozen_Test"},
		{"biglistbox-multiplerow-1", "IVT_Biglistbox_Multiplerow_1_Test"},
		{"biglistbox-multiplerow-1-frozen", "IVT_Biglistbox_Multiplerow_1_Frozen_Test"},
		{"biglistbox-multiplerow-min", "IVT_Biglistbox_Multiplerow_Min_Test"},
		{"biglistbox-multiplerow-min-frozen", "IVT_Biglistbox_Multiplerow_Min_Frozen_Test"},
		{"biglistbox-noheader-1", "IVT_Biglistbox_Noheader_1_Test"},
		{"biglistbox-noheader-1-frozen", "IVT_Biglistbox_Noheader_1_Frozen_Test"},
		{"biglistbox-noheader-min", "IVT_Biglistbox_Noheader_Min_Test"},
		{"biglistbox-noheader-min-frozen", "IVT_Biglistbox_Noheader_Min_Frozen_Test"},
		{"biglistbox-singlecolumn-1", "IVT_Biglistbox_Singlecolumn_1_Test"},
		{"biglistbox-singlecolumn-min", "IVT_Biglistbox_Singlecolumn_Min_Test"},
		{"biglistbox-singlerow-1", "IVT_Biglistbox_Singlerow_1_Test"},
		{"biglistbox-singlerow-1-frozen", "IVT_Biglistbox_Singlerow_1_Frozen_Test"},
		{"biglistbox-singlerow-min", "IVT_Biglistbox_Singlerow_Min_Test"},
		{"biglistbox-singlerow-min-frozen", "IVT_Biglistbox_Singlerow_Min_Frozen_Test"},
		{"borderlayout-autoscroll", "IVT_Borderlayout_Autoscroll_Test"},
		{"borderlayout-cmargins", "IVT_Borderlayout_Cmargins_Test"},
		{"borderlayout-collapsed-n", "IVT_Borderlayout_Collapsed_N_Test"},
		{"borderlayout-collapsed-ne", "IVT_Borderlayout_Collapsed_Ne_Test"},
		{"borderlayout-collapsed-nes", "IVT_Borderlayout_Collapsed_Nes_Test"},
		{"borderlayout-collapsed-nesw", "IVT_Borderlayout_Collapsed_Nesw_Test"},
		{"borderlayout-expanded", "IVT_Borderlayout_Expanded_Test"},
		{"borderlayout-margins", "IVT_Borderlayout_Margins_Test"},
		{"borderlayout-noborder", "IVT_Borderlayout_Noborder_Test"},
		{"borderlayout-simple", "IVT_Borderlayout_Simple_Test"},
		{"borderlayout-title", "IVT_Borderlayout_Title_Test"},
		{"button-hover", "IVT_Button_Hover_Test"},
		{"button-large", "IVT_Button_Large_Test"},
		{"button-longer", "IVT_Button_Longer_Test"},
		{"button-simple", "IVT_Button_Simple_Test"},
		{"calendar-simple", "IVT_Calendar_Simple_Test"},
		{"calendar-weekofyear", "IVT_Calendar_Weekofyear_Test"},
		{"caption-groupbox", "IVT_Caption_Groupbox_Test"},
		{"caption-groupbox-3d", "IVT_Caption_Groupbox_3D_Test"},
		{"caption-panel", "IVT_Caption_Panel_Test"},
		{"caption-window", "IVT_Caption_Window_Test"},
		{"checkbox-label", "IVT_Checkbox_Label_Test"},
		{"checkbox-simple", "IVT_Checkbox_Simple_Test"},
		{"chosenbox-base", "IVT_Chosenbox_Base_Test"},
		{"chosenbox-disabled", "IVT_Chosenbox_Disabled_Test"},
		{"chosenbox-nomodel", "IVT_Chosenbox_Nomodel_Test"},
		{"colorbox-basic", "IVT_Colorbox_Basic_Test"},
		{"colorbox-menu", "IVT_Colorbox_Menu_Test"},
		{"colorbox-toolbar", "IVT_Colorbox_Toolbar_Test"},
		{"combobox-description-icon", "IVT_Combobox_Description_Icon_Test"},
		{"combobox-only-description", "IVT_Combobox_Only_Description_Test"},
		{"combobox-only-icon", "IVT_Combobox_Only_Icon_Test"},
		{"combobox-simple", "IVT_Combobox_Simple_Test"},
		{"combobutton-menu", "IVT_Combobutton_Menu_Test"},
		{"combobutton-popup", "IVT_Combobutton_Popup_Test"},
		{"debug", "IVT_Debug_Test"},
		{"error", "IVT_Error_Test"},
		{"errorbox", "IVT_Errorbox_Test"},
		{"fisheyebar-horiz", "IVT_Fisheyebar_Horiz_Test"},
		{"fisheyebar-vert", "IVT_Fisheyebar_Vert_Test"},
		{"grid-detail", "IVT_Grid_Detail_Test"},
		{"grid-empty", "IVT_Grid_Empty_Test"},
		{"grid-grouping", "IVT_Grid_Grouping_Test"},
		{"grid-header-auxhead-auxhead-column", "IVT_Grid_Header_Auxhead_Auxhead_Column_Test"},
		{"grid-header-auxhead-column-auxhead", "IVT_Grid_Header_Auxhead_Column_Auxhead_Test"},
		{"grid-header-auxheader-textbox-datebox", "IVT_Grid_Header_Auxheader_Textbox_Datebox_Test"},
		{"grid-header-column-auxhead-auxhead", "IVT_Grid_Header_Column_Auxhead_Auxhead_Test"},
		{"grid-header-column-embedded", "IVT_Grid_Header_Column_Embedded_Test"},
		{"grid-header-no-auxhead-column", "IVT_Grid_Header_No_Auxhead_Column_Test"},
		{"grid-header-only-auxhead", "IVT_Grid_Header_Only_Auxhead_Test"},
		{"grid-header-only-column", "IVT_Grid_Header_Only_Column_Test"},
		{"grid-livegrouping", "IVT_Grid_Livegrouping_Test"},
		{"grid-paging-default-both", "IVT_Grid_Paging_Default_Both_Test"},
		{"grid-paging-default-bottom", "IVT_Grid_Paging_Default_Bottom_Test"},
		{"grid-paging-default-top", "IVT_Grid_Paging_Default_Top_Test"},
		{"grid-paging-multi", "IVT_Grid_Paging_Multi_Test"},
		{"grid-paging-onepage", "IVT_Grid_Paging_Onepage_Test"},
		{"grid-paging-os-both", "IVT_Grid_Paging_Os_Both_Test"},
		{"grid-paging-os-bottom", "IVT_Grid_Paging_Os_Bottom_Test"},
		{"grid-paging-os-top", "IVT_Grid_Paging_Os_Top_Test"},
		{"grid-sort-asc", "IVT_Grid_Sort_Asc_Test"},
		{"grid-sort-dsc", "IVT_Grid_Sort_Dsc_Test"},
		{"groupbox-3d-caption-image-only", "IVT_Groupbox_3D_Caption_Image_Only_Test"},
		{"groupbox-3d-caption-label-image", "IVT_Groupbox_3D_Caption_Label_Image_Test"},
		{"groupbox-3d-caption-label-only", "IVT_Groupbox_3D_Caption_Label_Only_Test"},
		{"groupbox-3d-no-caption", "IVT_Groupbox_3D_No_Caption_Test"},
		{"groupbox-caption-image-only", "IVT_Groupbox_Caption_Image_Only_Test"},
		{"groupbox-caption-label-image", "IVT_Groupbox_Caption_Label_Image_Test"},
		{"groupbox-caption-label-only", "IVT_Groupbox_Caption_Label_Only_Test"},
		{"groupbox-no-caption", "IVT_Groupbox_No_Caption_Test"},
		{"inputs-combo-disabled", "IVT_Inputs_Combo_Disabled_Test"},
		{"inputs-combo-inplace", "IVT_Inputs_Combo_Inplace_Test"},
		{"inputs-combo-normal", "IVT_Inputs_Combo_Normal_Test"},
		{"inputs-combo-readonly", "IVT_Inputs_Combo_Readonly_Test"},
		{"inputs-combo-rounded-disabled", "IVT_Inputs_Combo_Rounded_Disabled_Test"},
		{"inputs-combo-rounded-inplace", "IVT_Inputs_Combo_Rounded_Inplace_Test"},
		{"inputs-combo-rounded-normal", "IVT_Inputs_Combo_Rounded_Normal_Test"},
		{"inputs-combo-rounded-readonly", "IVT_Inputs_Combo_Rounded_Readonly_Test"},
		{"inputs-disabled", "IVT_Inputs_Disabled_Test"},
		{"inputs-inplace", "IVT_Inputs_Inplace_Test"},
		{"inputs-normal", "IVT_Inputs_Normal_Test"},
		{"inputs-readonly", "IVT_Inputs_Readonly_Test"},
		{"inputs-rounded-disabled", "IVT_Inputs_Rounded_Disabled_Test"},
		{"inputs-rounded-inplace", "IVT_Inputs_Rounded_Inplace_Test"},
		{"inputs-rounded-normal", "IVT_Inputs_Rounded_Normal_Test"},
		{"inputs-rounded-readonly", "IVT_Inputs_Rounded_Readonly_Test"},
		{"jq-alert", "IVT_Jq_Alert_Test"},
		{"listbox-checkmark", "IVT_Listbox_Checkmark_Test"},
		{"listbox-checkmark-single", "IVT_Listbox_Checkmark_Single_Test"},
		{"listbox-empty", "IVT_Listbox_Empty_Test"},
		{"listbox-grouping", "IVT_Listbox_Grouping_Test"},
		{"listbox-header-auxhead-auxhead-listhead", "IVT_Listbox_Header_Auxhead_Auxhead_Listhead_Test"},
		{"listbox-header-auxhead-listhead-auxhead", "IVT_Listbox_Header_Auxhead_Listhead_Auxhead_Test"},
		{"listbox-header-complex", "IVT_Listbox_Header_Complex_Test"},
		{"listbox-header-grouping", "IVT_Listbox_Header_Grouping_Test"},
		{"listbox-header-grouping-height", "IVT_Listbox_Header_Grouping_Height_Test"},
		{"listbox-header-grouping-paging-default-both", "IVT_Listbox_Header_Grouping_Paging_Default_Both_Test"},
		{"listbox-header-grouping-paging-default-bottom", "IVT_Listbox_Header_Grouping_Paging_Default_Bottom_Test"},
		{"listbox-header-grouping-paging-default-top", "IVT_Listbox_Header_Grouping_Paging_Default_Top_Test"},
		{"listbox-header-grouping-paging-os-both", "IVT_Listbox_Header_Grouping_Paging_Os_Both_Test"},
		{"listbox-header-grouping-paging-os-bottom", "IVT_Listbox_Header_Grouping_Paging_Os_Bottom_Test"},
		{"listbox-header-grouping-paging-os-top", "IVT_Listbox_Header_Grouping_Paging_Os_Top_Test"},
		{"listbox-header-listhead-auxhead-auxhead", "IVT_Listbox_Header_Listhead_Auxhead_Auxhead_Test"},
		{"listbox-listcell-label-image", "IVT_Listbox_Listcell_Label_Image_Test"},
		{"listbox-livedata", "IVT_Listbox_Livedata_Test"},
		{"listbox-paging-default-both", "IVT_Listbox_Paging_Default_Both_Test"},
		{"listbox-paging-default-bottom", "IVT_Listbox_Paging_Default_Bottom_Test"},
		{"listbox-paging-default-top", "IVT_Listbox_Paging_Default_Top_Test"},
		{"listbox-paging-os-both", "IVT_Listbox_Paging_Os_Both_Test"},
		{"listbox-paging-os-bottom", "IVT_Listbox_Paging_Os_Bottom_Test"},
		{"listbox-paging-os-top", "IVT_Listbox_Paging_Os_Top_Test"},
		{"listbox-select", "IVT_Listbox_Select_Test"},
		{"listbox-sorting-sizable", "IVT_Listbox_Sorting_Sizable_Test"},
		{"listbox-sorting-sizable-checkmark", "IVT_Listbox_Sorting_Sizable_Checkmark_Test"},
		{"listbox-sorting-sizable-header", "IVT_Listbox_Sorting_Sizable_Header_Test"},
		{"loading-busy", "IVT_Loading_Busy_Test"},
		{"loading-busy-closable", "IVT_Loading_Busy_Closable_Test"},
		{"loading-render-defer", "IVT_Loading_Render_Defer_Test"},
		{"menubar-autodrop", "IVT_Menubar_Autodrop_Test"},
		{"menubar-horizontal", "IVT_Menubar_Horizontal_Test"},
		{"menubar-scrollable", "IVT_Menubar_Scrollable_Test"},
		{"menubar-vertical", "IVT_Menubar_Vertical_Test"},
		{"menu-colorpicker", "IVT_Menu_Colorpicker_Test"},
		{"menupopup", "IVT_Menupopup_Test"},
		{"messagebox-error", "IVT_Messagebox_Error_Test"},
		{"messagebox-information", "IVT_Messagebox_Information_Test"},
		{"messagebox-longer-error", "IVT_Messagebox_Longer_Error_Test"},
		{"messagebox-longer-information", "IVT_Messagebox_Longer_Information_Test"},
		{"messagebox-longer-question", "IVT_Messagebox_Longer_Question_Test"},
		{"messagebox-longer-warning", "IVT_Messagebox_Longer_Warning_Test"},
		{"messagebox-question", "IVT_Messagebox_Question_Test"},
		{"messagebox-verylong", "IVT_Messagebox_Verylong_Test"},
		{"messagebox-warning", "IVT_Messagebox_Warning_Test"},
		{"notification-error-after_pointer", "IVT_Notification_Error_After_Pointer_Test"},
		{"notification-error-at_pointer", "IVT_Notification_Error_At_Pointer_Test"},
		{"notification-error-bottom_center", "IVT_Notification_Error_Bottom_Center_Test"},
		{"notification-error-bottom_left", "IVT_Notification_Error_Bottom_Left_Test"},
		{"notification-error-bottom_right", "IVT_Notification_Error_Bottom_Right_Test"},
		{"notification-error-closable-after_pointer", "IVT_Notification_Error_Closable_After_Pointer_Test"},
		{"notification-error-closable-at_pointer", "IVT_Notification_Error_Closable_At_Pointer_Test"},
		{"notification-error-closable-bottom_center", "IVT_Notification_Error_Closable_Bottom_Center_Test"},
		{"notification-error-closable-bottom_left", "IVT_Notification_Error_Closable_Bottom_Left_Test"},
		{"notification-error-closable-bottom_right", "IVT_Notification_Error_Closable_Bottom_Right_Test"},
		{"notification-error-closable-default", "IVT_Notification_Error_Closable_Default_Test"},
		{"notification-error-closable-middle_center", "IVT_Notification_Error_Closable_Middle_Center_Test"},
		{"notification-error-closable-middle_left", "IVT_Notification_Error_Closable_Middle_Left_Test"},
		{"notification-error-closable-middle_right", "IVT_Notification_Error_Closable_Middle_Right_Test"},
		{"notification-error-closable-top_center", "IVT_Notification_Error_Closable_Top_Center_Test"},
		{"notification-error-closable-top_left", "IVT_Notification_Error_Closable_Top_Left_Test"},
		{"notification-error-closable-top_right", "IVT_Notification_Error_Closable_Top_Right_Test"},
		{"notification-error-closable-xy", "IVT_Notification_Error_Closable_Xy_Test"},
		{"notification-error-default", "IVT_Notification_Error_Default_Test"},
		{"notification-error-middle_center", "IVT_Notification_Error_Middle_Center_Test"},
		{"notification-error-middle_left", "IVT_Notification_Error_Middle_Left_Test"},
		{"notification-error-middle_right", "IVT_Notification_Error_Middle_Right_Test"},
		{"notification-error-top_center", "IVT_Notification_Error_Top_Center_Test"},
		{"notification-error-top_left", "IVT_Notification_Error_Top_Left_Test"},
		{"notification-error-top_right", "IVT_Notification_Error_Top_Right_Test"},
		{"notification-error-xy", "IVT_Notification_Error_Xy_Test"},
		{"notification-info-after_pointer", "IVT_Notification_Info_After_Pointer_Test"},
		{"notification-info-at_pointer", "IVT_Notification_Info_At_Pointer_Test"},
		{"notification-info-bottom_center", "IVT_Notification_Info_Bottom_Center_Test"},
		{"notification-info-bottom_left", "IVT_Notification_Info_Bottom_Left_Test"},
		{"notification-info-bottom_right", "IVT_Notification_Info_Bottom_Right_Test"},
		{"notification-info-closable-after_pointer", "IVT_Notification_Info_Closable_After_Pointer_Test"},
		{"notification-info-closable-at_pointer", "IVT_Notification_Info_Closable_At_Pointer_Test"},
		{"notification-info-closable-bottom_center", "IVT_Notification_Info_Closable_Bottom_Center_Test"},
		{"notification-info-closable-bottom_left", "IVT_Notification_Info_Closable_Bottom_Left_Test"},
		{"notification-info-closable-bottom_right", "IVT_Notification_Info_Closable_Bottom_Right_Test"},
		{"notification-info-closable-default", "IVT_Notification_Info_Closable_Default_Test"},
		{"notification-info-closable-middle_center", "IVT_Notification_Info_Closable_Middle_Center_Test"},
		{"notification-info-closable-middle_left", "IVT_Notification_Info_Closable_Middle_Left_Test"},
		{"notification-info-closable-middle_right", "IVT_Notification_Info_Closable_Middle_Right_Test"},
		{"notification-info-closable-top_center", "IVT_Notification_Info_Closable_Top_Center_Test"},
		{"notification-info-closable-top_left", "IVT_Notification_Info_Closable_Top_Left_Test"},
		{"notification-info-closable-top_right", "IVT_Notification_Info_Closable_Top_Right_Test"},
		{"notification-info-closable-xy", "IVT_Notification_Info_Closable_Xy_Test"},
		{"notification-info-default", "IVT_Notification_Info_Default_Test"},
		{"notification-info-middle_center", "IVT_Notification_Info_Middle_Center_Test"},
		{"notification-info-middle_left", "IVT_Notification_Info_Middle_Left_Test"},
		{"notification-info-middle_right", "IVT_Notification_Info_Middle_Right_Test"},
		{"notification-info-top_center", "IVT_Notification_Info_Top_Center_Test"},
		{"notification-info-top_left", "IVT_Notification_Info_Top_Left_Test"},
		{"notification-info-top_right", "IVT_Notification_Info_Top_Right_Test"},
		{"notification-info-xy", "IVT_Notification_Info_Xy_Test"},
		{"notification-ref-error-after_center", "IVT_Notification_Ref_Error_After_Center_Test"},
		{"notification-ref-error-after_end", "IVT_Notification_Ref_Error_After_End_Test"},
		{"notification-ref-error-after_start", "IVT_Notification_Ref_Error_After_Start_Test"},
		{"notification-ref-error-before_center", "IVT_Notification_Ref_Error_Before_Center_Test"},
		{"notification-ref-error-before_end", "IVT_Notification_Ref_Error_Before_End_Test"},
		{"notification-ref-error-before_start", "IVT_Notification_Ref_Error_Before_Start_Test"},
		{"notification-ref-error-bottom_center", "IVT_Notification_Ref_Error_Bottom_Center_Test"},
		{"notification-ref-error-bottom_left", "IVT_Notification_Ref_Error_Bottom_Left_Test"},
		{"notification-ref-error-bottom_right", "IVT_Notification_Ref_Error_Bottom_Right_Test"},
		{"notification-ref-error-closable-after_center", "IVT_Notification_Ref_Error_Closable_After_Center_Test"},
		{"notification-ref-error-closable-after_end", "IVT_Notification_Ref_Error_Closable_After_End_Test"},
		{"notification-ref-error-closable-after_start", "IVT_Notification_Ref_Error_Closable_After_Start_Test"},
		{"notification-ref-error-closable-before_center", "IVT_Notification_Ref_Error_Closable_Before_Center_Test"},
		{"notification-ref-error-closable-before_end", "IVT_Notification_Ref_Error_Closable_Before_End_Test"},
		{"notification-ref-error-closable-before_start", "IVT_Notification_Ref_Error_Closable_Before_Start_Test"},
		{"notification-ref-error-closable-bottom_center", "IVT_Notification_Ref_Error_Closable_Bottom_Center_Test"},
		{"notification-ref-error-closable-bottom_left", "IVT_Notification_Ref_Error_Closable_Bottom_Left_Test"},
		{"notification-ref-error-closable-bottom_right", "IVT_Notification_Ref_Error_Closable_Bottom_Right_Test"},
		{"notification-ref-error-closable-default", "IVT_Notification_Ref_Error_Closable_Default_Test"},
		{"notification-ref-error-closable-end_after", "IVT_Notification_Ref_Error_Closable_End_After_Test"},
		{"notification-ref-error-closable-end_before", "IVT_Notification_Ref_Error_Closable_End_Before_Test"},
		{"notification-ref-error-closable-end_center", "IVT_Notification_Ref_Error_Closable_End_Center_Test"},
		{"notification-ref-error-closable-middle_center", "IVT_Notification_Ref_Error_Closable_Middle_Center_Test"},
		{"notification-ref-error-closable-middle_left", "IVT_Notification_Ref_Error_Closable_Middle_Left_Test"},
		{"notification-ref-error-closable-middle_right", "IVT_Notification_Ref_Error_Closable_Middle_Right_Test"},
		{"notification-ref-error-closable-start_after", "IVT_Notification_Ref_Error_Closable_Start_After_Test"},
		{"notification-ref-error-closable-start_before", "IVT_Notification_Ref_Error_Closable_Start_Before_Test"},
		{"notification-ref-error-closable-start_center", "IVT_Notification_Ref_Error_Closable_Start_Center_Test"},
		{"notification-ref-error-closable-top_center", "IVT_Notification_Ref_Error_Closable_Top_Center_Test"},
		{"notification-ref-error-closable-top_left", "IVT_Notification_Ref_Error_Closable_Top_Left_Test"},
		{"notification-ref-error-closable-top_right", "IVT_Notification_Ref_Error_Closable_Top_Right_Test"},
		{"notification-ref-error-default", "IVT_Notification_Ref_Error_Default_Test"},
		{"notification-ref-error-end_after", "IVT_Notification_Ref_Error_End_After_Test"},
		{"notification-ref-error-end_before", "IVT_Notification_Ref_Error_End_Before_Test"},
		{"notification-ref-error-end_center", "IVT_Notification_Ref_Error_End_Center_Test"},
		{"notification-ref-error-middle_center", "IVT_Notification_Ref_Error_Middle_Center_Test"},
		{"notification-ref-error-middle_left", "IVT_Notification_Ref_Error_Middle_Left_Test"},
		{"notification-ref-error-middle_right", "IVT_Notification_Ref_Error_Middle_Right_Test"},
		{"notification-ref-error-start_after", "IVT_Notification_Ref_Error_Start_After_Test"},
		{"notification-ref-error-start_before", "IVT_Notification_Ref_Error_Start_Before_Test"},
		{"notification-ref-error-start_center", "IVT_Notification_Ref_Error_Start_Center_Test"},
		{"notification-ref-error-top_center", "IVT_Notification_Ref_Error_Top_Center_Test"},
		{"notification-ref-error-top_left", "IVT_Notification_Ref_Error_Top_Left_Test"},
		{"notification-ref-error-top_right", "IVT_Notification_Ref_Error_Top_Right_Test"},
		{"notification-ref-info-after_center", "IVT_Notification_Ref_Info_After_Center_Test"},
		{"notification-ref-info-after_end", "IVT_Notification_Ref_Info_After_End_Test"},
		{"notification-ref-info-after_start", "IVT_Notification_Ref_Info_After_Start_Test"},
		{"notification-ref-info-before_center", "IVT_Notification_Ref_Info_Before_Center_Test"},
		{"notification-ref-info-before_end", "IVT_Notification_Ref_Info_Before_End_Test"},
		{"notification-ref-info-before_start", "IVT_Notification_Ref_Info_Before_Start_Test"},
		{"notification-ref-info-bottom_center", "IVT_Notification_Ref_Info_Bottom_Center_Test"},
		{"notification-ref-info-bottom_left", "IVT_Notification_Ref_Info_Bottom_Left_Test"},
		{"notification-ref-info-bottom_right", "IVT_Notification_Ref_Info_Bottom_Right_Test"},
		{"notification-ref-info-closable-after_center", "IVT_Notification_Ref_Info_Closable_After_Center_Test"},
		{"notification-ref-info-closable-after_end", "IVT_Notification_Ref_Info_Closable_After_End_Test"},
		{"notification-ref-info-closable-after_start", "IVT_Notification_Ref_Info_Closable_After_Start_Test"},
		{"notification-ref-info-closable-before_center", "IVT_Notification_Ref_Info_Closable_Before_Center_Test"},
		{"notification-ref-info-closable-before_end", "IVT_Notification_Ref_Info_Closable_Before_End_Test"},
		{"notification-ref-info-closable-before_start", "IVT_Notification_Ref_Info_Closable_Before_Start_Test"},
		{"notification-ref-info-closable-bottom_center", "IVT_Notification_Ref_Info_Closable_Bottom_Center_Test"},
		{"notification-ref-info-closable-bottom_left", "IVT_Notification_Ref_Info_Closable_Bottom_Left_Test"},
		{"notification-ref-info-closable-bottom_right", "IVT_Notification_Ref_Info_Closable_Bottom_Right_Test"},
		{"notification-ref-info-closable-default", "IVT_Notification_Ref_Info_Closable_Default_Test"},
		{"notification-ref-info-closable-end_after", "IVT_Notification_Ref_Info_Closable_End_After_Test"},
		{"notification-ref-info-closable-end_before", "IVT_Notification_Ref_Info_Closable_End_Before_Test"},
		{"notification-ref-info-closable-end_center", "IVT_Notification_Ref_Info_Closable_End_Center_Test"},
		{"notification-ref-info-closable-middle_center", "IVT_Notification_Ref_Info_Closable_Middle_Center_Test"},
		{"notification-ref-info-closable-middle_left", "IVT_Notification_Ref_Info_Closable_Middle_Left_Test"},
		{"notification-ref-info-closable-middle_right", "IVT_Notification_Ref_Info_Closable_Middle_Right_Test"},
		{"notification-ref-info-closable-start_after", "IVT_Notification_Ref_Info_Closable_Start_After_Test"},
		{"notification-ref-info-closable-start_before", "IVT_Notification_Ref_Info_Closable_Start_Before_Test"},
		{"notification-ref-info-closable-start_center", "IVT_Notification_Ref_Info_Closable_Start_Center_Test"},
		{"notification-ref-info-closable-top_center", "IVT_Notification_Ref_Info_Closable_Top_Center_Test"},
		{"notification-ref-info-closable-top_left", "IVT_Notification_Ref_Info_Closable_Top_Left_Test"},
		{"notification-ref-info-closable-top_right", "IVT_Notification_Ref_Info_Closable_Top_Right_Test"},
		{"notification-ref-info-default", "IVT_Notification_Ref_Info_Default_Test"},
		{"notification-ref-info-end_after", "IVT_Notification_Ref_Info_End_After_Test"},
		{"notification-ref-info-end_before", "IVT_Notification_Ref_Info_End_Before_Test"},
		{"notification-ref-info-end_center", "IVT_Notification_Ref_Info_End_Center_Test"},
		{"notification-ref-info-middle_center", "IVT_Notification_Ref_Info_Middle_Center_Test"},
		{"notification-ref-info-middle_left", "IVT_Notification_Ref_Info_Middle_Left_Test"},
		{"notification-ref-info-middle_right", "IVT_Notification_Ref_Info_Middle_Right_Test"},
		{"notification-ref-info-start_after", "IVT_Notification_Ref_Info_Start_After_Test"},
		{"notification-ref-info-start_before", "IVT_Notification_Ref_Info_Start_Before_Test"},
		{"notification-ref-info-start_center", "IVT_Notification_Ref_Info_Start_Center_Test"},
		{"notification-ref-info-top_center", "IVT_Notification_Ref_Info_Top_Center_Test"},
		{"notification-ref-info-top_left", "IVT_Notification_Ref_Info_Top_Left_Test"},
		{"notification-ref-info-top_right", "IVT_Notification_Ref_Info_Top_Right_Test"},
		{"notification-ref-warning-after_center", "IVT_Notification_Ref_Warning_After_Center_Test"},
		{"notification-ref-warning-after_end", "IVT_Notification_Ref_Warning_After_End_Test"},
		{"notification-ref-warning-after_start", "IVT_Notification_Ref_Warning_After_Start_Test"},
		{"notification-ref-warning-before_center", "IVT_Notification_Ref_Warning_Before_Center_Test"},
		{"notification-ref-warning-before_end", "IVT_Notification_Ref_Warning_Before_End_Test"},
		{"notification-ref-warning-before_start", "IVT_Notification_Ref_Warning_Before_Start_Test"},
		{"notification-ref-warning-bottom_center", "IVT_Notification_Ref_Warning_Bottom_Center_Test"},
		{"notification-ref-warning-bottom_left", "IVT_Notification_Ref_Warning_Bottom_Left_Test"},
		{"notification-ref-warning-bottom_right", "IVT_Notification_Ref_Warning_Bottom_Right_Test"},
		{"notification-ref-warning-closable-after_center", "IVT_Notification_Ref_Warning_Closable_After_Center_Test"},
		{"notification-ref-warning-closable-after_end", "IVT_Notification_Ref_Warning_Closable_After_End_Test"},
		{"notification-ref-warning-closable-after_start", "IVT_Notification_Ref_Warning_Closable_After_Start_Test"},
		{"notification-ref-warning-closable-before_center", "IVT_Notification_Ref_Warning_Closable_Before_Center_Test"},
		{"notification-ref-warning-closable-before_end", "IVT_Notification_Ref_Warning_Closable_Before_End_Test"},
		{"notification-ref-warning-closable-before_start", "IVT_Notification_Ref_Warning_Closable_Before_Start_Test"},
		{"notification-ref-warning-closable-bottom_center", "IVT_Notification_Ref_Warning_Closable_Bottom_Center_Test"},
		{"notification-ref-warning-closable-bottom_left", "IVT_Notification_Ref_Warning_Closable_Bottom_Left_Test"},
		{"notification-ref-warning-closable-bottom_right", "IVT_Notification_Ref_Warning_Closable_Bottom_Right_Test"},
		{"notification-ref-warning-closable-default", "IVT_Notification_Ref_Warning_Closable_Default_Test"},
		{"notification-ref-warning-closable-end_after", "IVT_Notification_Ref_Warning_Closable_End_After_Test"},
		{"notification-ref-warning-closable-end_before", "IVT_Notification_Ref_Warning_Closable_End_Before_Test"},
		{"notification-ref-warning-closable-end_center", "IVT_Notification_Ref_Warning_Closable_End_Center_Test"},
		{"notification-ref-warning-closable-middle_center", "IVT_Notification_Ref_Warning_Closable_Middle_Center_Test"},
		{"notification-ref-warning-closable-middle_left", "IVT_Notification_Ref_Warning_Closable_Middle_Left_Test"},
		{"notification-ref-warning-closable-middle_right", "IVT_Notification_Ref_Warning_Closable_Middle_Right_Test"},
		{"notification-ref-warning-closable-start_after", "IVT_Notification_Ref_Warning_Closable_Start_After_Test"},
		{"notification-ref-warning-closable-start_before", "IVT_Notification_Ref_Warning_Closable_Start_Before_Test"},
		{"notification-ref-warning-closable-start_center", "IVT_Notification_Ref_Warning_Closable_Start_Center_Test"},
		{"notification-ref-warning-closable-top_center", "IVT_Notification_Ref_Warning_Closable_Top_Center_Test"},
		{"notification-ref-warning-closable-top_left", "IVT_Notification_Ref_Warning_Closable_Top_Left_Test"},
		{"notification-ref-warning-closable-top_right", "IVT_Notification_Ref_Warning_Closable_Top_Right_Test"},
		{"notification-ref-warning-default", "IVT_Notification_Ref_Warning_Default_Test"},
		{"notification-ref-warning-end_after", "IVT_Notification_Ref_Warning_End_After_Test"},
		{"notification-ref-warning-end_before", "IVT_Notification_Ref_Warning_End_Before_Test"},
		{"notification-ref-warning-end_center", "IVT_Notification_Ref_Warning_End_Center_Test"},
		{"notification-ref-warning-middle_center", "IVT_Notification_Ref_Warning_Middle_Center_Test"},
		{"notification-ref-warning-middle_left", "IVT_Notification_Ref_Warning_Middle_Left_Test"},
		{"notification-ref-warning-middle_right", "IVT_Notification_Ref_Warning_Middle_Right_Test"},
		{"notification-ref-warning-start_after", "IVT_Notification_Ref_Warning_Start_After_Test"},
		{"notification-ref-warning-start_before", "IVT_Notification_Ref_Warning_Start_Before_Test"},
		{"notification-ref-warning-start_center", "IVT_Notification_Ref_Warning_Start_Center_Test"},
		{"notification-ref-warning-top_center", "IVT_Notification_Ref_Warning_Top_Center_Test"},
		{"notification-ref-warning-top_left", "IVT_Notification_Ref_Warning_Top_Left_Test"},
		{"notification-ref-warning-top_right", "IVT_Notification_Ref_Warning_Top_Right_Test"},
		{"notification-warning-after_pointer", "IVT_Notification_Warning_After_Pointer_Test"},
		{"notification-warning-at_pointer", "IVT_Notification_Warning_At_Pointer_Test"},
		{"notification-warning-bottom_center", "IVT_Notification_Warning_Bottom_Center_Test"},
		{"notification-warning-bottom_left", "IVT_Notification_Warning_Bottom_Left_Test"},
		{"notification-warning-bottom_right", "IVT_Notification_Warning_Bottom_Right_Test"},
		{"notification-warning-closable-after_pointer", "IVT_Notification_Warning_Closable_After_Pointer_Test"},
		{"notification-warning-closable-at_pointer", "IVT_Notification_Warning_Closable_At_Pointer_Test"},
		{"notification-warning-closable-bottom_center", "IVT_Notification_Warning_Closable_Bottom_Center_Test"},
		{"notification-warning-closable-bottom_left", "IVT_Notification_Warning_Closable_Bottom_Left_Test"},
		{"notification-warning-closable-bottom_right", "IVT_Notification_Warning_Closable_Bottom_Right_Test"},
		{"notification-warning-closable-default", "IVT_Notification_Warning_Closable_Default_Test"},
		{"notification-warning-closable-middle_center", "IVT_Notification_Warning_Closable_Middle_Center_Test"},
		{"notification-warning-closable-middle_left", "IVT_Notification_Warning_Closable_Middle_Left_Test"},
		{"notification-warning-closable-middle_right", "IVT_Notification_Warning_Closable_Middle_Right_Test"},
		{"notification-warning-closable-top_center", "IVT_Notification_Warning_Closable_Top_Center_Test"},
		{"notification-warning-closable-top_left", "IVT_Notification_Warning_Closable_Top_Left_Test"},
		{"notification-warning-closable-top_right", "IVT_Notification_Warning_Closable_Top_Right_Test"},
		{"notification-warning-closable-xy", "IVT_Notification_Warning_Closable_Xy_Test"},
		{"notification-warning-default", "IVT_Notification_Warning_Default_Test"},
		{"notification-warning-middle_center", "IVT_Notification_Warning_Middle_Center_Test"},
		{"notification-warning-middle_left", "IVT_Notification_Warning_Middle_Left_Test"},
		{"notification-warning-middle_right", "IVT_Notification_Warning_Middle_Right_Test"},
		{"notification-warning-top_center", "IVT_Notification_Warning_Top_Center_Test"},
		{"notification-warning-top_left", "IVT_Notification_Warning_Top_Left_Test"},
		{"notification-warning-top_right", "IVT_Notification_Warning_Top_Right_Test"},
		{"notification-warning-xy", "IVT_Notification_Warning_Xy_Test"},
		{"radio-label", "IVT_Radio_Label_Test"},
		{"radio-simple", "IVT_Radio_Simple_Test"},
		{"textbox-multiline", "IVT_Textbox_Multiline_Test"},
		{"textbox-rounded-multiline", "IVT_Textbox_Rounded_Multiline_Test"}
	};

	public static void main(String[] args) {
		int count = 0;
		
		for (String[] mapping : mappings) {
			String srcName = mapping[0];
			String dstName = mapping[1];
			
			File srcFile = new File(srcPath, srcName + "");
			File dstFile = new File(dstPath, dstName + ".scala");
			
			try {
	            PrintWriter out = 
	            	new PrintWriter(new BufferedWriter(new FileWriter(dstFile)));
	            
	            out.println("package org.zkoss.zktest.test2.theme.ipad;");
	            out.println();
	            out.println("import org.zkoss.zstl.ZTL4ScalaTestCase;");
	            out.println("import org.zkoss.ztl.Tags");
	            out.println();
	            out.println("@Tags(tags = \"IOS,VisionTest\")");
	            out.printf("class %s extends ZTL4ScalaTestCase {%n", dstName);
	        	out.println("\tdef testClick() = {");
	        	out.println("\t\tval zscript = \"\"\"");
	        	
	        	BufferedReader br =
	        		new BufferedReader(new FileReader(srcFile));
	        	String line = null;
	        	while ((line = br.readLine()) != null) {
	        		out.println(line);
	        	}
	        	br.close();
	        	
	        	out.println("\t\t\"\"\";");
	        	out.println();
	        	out.println("\t\trunZTL(zscript,");
	    		out.println("\t\t\t() => {");
	    		out.println("\t\t\t\tverifyImage();");
	    		out.println("\t\t\t});");
	    		out.println("\t}");
				out.println("}");
				
				out.close();
				
				System.out.println("Processed " + srcName + "");
            } catch (IOException e) {
	            e.printStackTrace();
            }
			
		}
	}

}
